# Generated by Django 3.2.5 on 2021-11-20 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMMEDIATE', 'Intermmediate'), ('ADVANCED', 'Advanced')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain at least 3 letters or numbers', regex='^\\w{3,}$')]),
        ),
    ]
