# Generated by Django 3.2.5 on 2021-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20211120_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMMEDIATE', 'Intermmediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
    ]
