# Generated by Django 3.2.5 on 2021-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_user_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('MEMBER', 'Member'), ('OFFICER', 'Officer'), ('OWNER', 'Owner')], default='MEMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
    ]
