# Generated by Django 3.2.5 on 2021-11-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20211122_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
