# Generated by Django 3.2.5 on 2021-11-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_user_user_type'),
        ('clubs', '0008_user_user_type'),
    ]

    operations = [
    ]
