# Generated by Django 3.2.5 on 2021-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_merge_0007_alter_user_user_type_0008_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
