# Generated by Django 3.2.5 on 2021-12-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_user_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
